"""Add year_of_study/field_of_study to posts

Revision ID: 05919cfa55dd
Revises: 69715a85340a
Create Date: 2025-11-04 07:49:56.982844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05919cfa55dd'
down_revision = '69715a85340a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_of_study', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('field_of_study', sa.String(length=100), nullable=True))

    with op.batch_alter_table('flashcard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_of_study', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('field_of_study', sa.String(length=100), nullable=True))

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_of_study', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('field_of_study', sa.String(length=100), nullable=True))

    with op.batch_alter_table('ressource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_of_study', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ressource', schema=None) as batch_op:
        batch_op.drop_column('field_of_study')

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('field_of_study')
        batch_op.drop_column('year_of_study')

    with op.batch_alter_table('flashcard', schema=None) as batch_op:
        batch_op.drop_column('field_of_study')
        batch_op.drop_column('year_of_study')

    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.drop_column('field_of_study')
        batch_op.drop_column('year_of_study')

    # ### end Alembic commands ###
