"""update

Revision ID: a80f0a84a294
Revises: a2d9c2eb4879
Create Date: 2025-09-20 18:29:41.344397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a80f0a84a294'
down_revision = 'a2d9c2eb4879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ressource', schema=None) as batch_op:
        batch_op.drop_column('download_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ressource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('download_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
